"""add_soft_delete_to_properties

Revision ID: 097988b6b704
Revises: 00263471ef5f
Create Date: 2026-07-05 22:53:33.780373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097988b6b704'
down_revision: Union[str, Sequence[str], None] = '00263471ef5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('deleted_by', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'deleted_by')
    op.drop_column('properties', 'deleted_at')
    # ### end Alembic commands ###
