"""doc

Revision ID: 310bce7da380
Revises: 55905b8cb2a1
Create Date: 2026-06-26 15:38:17.704037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310bce7da380'
down_revision: Union[str, Sequence[str], None] = '55905b8cb2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('deduction_notice_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.Enum('message', 'formal_letter', name='doc_type'), nullable=False),
    sa.Column('status', sa.Enum('processing', 'draft', 'sent', 'failed', name='doc_status'), nullable=False),
    sa.Column('ai_draft', sa.Text(), nullable=True),
    sa.Column('edited_content', sa.Text(), nullable=True, comment="User's edited version. Display this over ai_draft when present."),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deduction_notice_id'], ['deduction_notices.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_deduction_notice_id'), 'generated_documents', ['deduction_notice_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_property_id'), 'generated_documents', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_documents_property_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_deduction_notice_id'), table_name='generated_documents')
    op.drop_table('generated_documents')
    # ### end Alembic commands ###
