"""dispute

Revision ID: 3ffc85d29255
Revises: eb4b45667aec
Create Date: 2026-06-26 14:16:59.025853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ffc85d29255'
down_revision: Union[str, Sequence[str], None] = 'eb4b45667aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduction_notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', name='notice_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deduction_notices_property_id'), 'deduction_notices', ['property_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deduction_notice_id', sa.UUID(), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('label', sa.Enum('supported', 'weak', 'unsupported', 'unclear', name='claim_label'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_override_label', sa.Enum('supported', 'weak', 'unsupported', 'unclear', name='claim_label'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deduction_notice_id'], ['deduction_notices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_deduction_notice_id'), 'claims', ['deduction_notice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_deduction_notice_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_deduction_notices_property_id'), table_name='deduction_notices')
    op.drop_table('deduction_notices')
    # ### end Alembic commands ###
