"""add evidence management columns

Revision ID: 98346377a60b
Revises: b50cde1ef2e7
Create Date: 2026-07-05 15:42:07.328860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98346377a60b'
down_revision: Union[str, Sequence[str], None] = 'b50cde1ef2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('evidence', sa.Column('display_name', sa.String(length=200), server_default='Evidence File', nullable=False))
    op.add_column('evidence', sa.Column('category', sa.String(length=50), server_default='other', nullable=False))
    op.add_column('evidence', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('evidence', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('evidence', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('evidence', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('evidence', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('evidence', sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evidence', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evidence', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_evidence_category'), 'evidence', ['category'], unique=False)
    op.create_index(op.f('ix_evidence_deleted_at'), 'evidence', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_evidence_file_hash'), 'evidence', ['file_hash'], unique=False)
    op.create_index(op.f('ix_evidence_sort_order'), 'evidence', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_sort_order'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_file_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_deleted_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_category'), table_name='evidence')
    op.drop_column('evidence', 'deleted_by')
    op.drop_column('evidence', 'deleted_at')
    op.drop_column('evidence', 'captured_at')
    op.drop_column('evidence', 'height')
    op.drop_column('evidence', 'width')
    op.drop_column('evidence', 'file_size')
    op.drop_column('evidence', 'mime_type')
    op.drop_column('evidence', 'sort_order')
    op.drop_column('evidence', 'category')
    op.drop_column('evidence', 'display_name')
    op.drop_column('evidence', 'file_hash')
    # ### end Alembic commands ###
