"""add hash and is_active columns

Revision ID: b50cde1ef2e7
Revises: d5f83c5297f9
Create Date: 2026-07-05 15:20:00.250730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50cde1ef2e7'
down_revision: Union[str, Sequence[str], None] = 'd5f83c5297f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_claims_is_active'), 'claims', ['is_active'], unique=False)
    op.add_column('deduction_notices', sa.Column('notice_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_deduction_notices_notice_hash'), 'deduction_notices', ['notice_hash'], unique=False)
    op.add_column('generated_documents', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_generated_documents_is_active'), 'generated_documents', ['is_active'], unique=False)
    op.add_column('leases', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_leases_file_hash'), 'leases', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leases_file_hash'), table_name='leases')
    op.drop_column('leases', 'file_hash')
    op.drop_index(op.f('ix_generated_documents_is_active'), table_name='generated_documents')
    op.drop_column('generated_documents', 'is_active')
    op.drop_index(op.f('ix_deduction_notices_notice_hash'), table_name='deduction_notices')
    op.drop_column('deduction_notices', 'notice_hash')
    op.drop_index(op.f('ix_claims_is_active'), table_name='claims')
    op.drop_column('claims', 'is_active')
    # ### end Alembic commands ###
