"""add error_message to generated_documents

Revision ID: d5f83c5297f9
Revises: 310bce7da380
Create Date: 2026-07-05 15:08:29.339593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f83c5297f9'
down_revision: Union[str, Sequence[str], None] = '310bce7da380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_documents', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_documents', 'error_message')
    # ### end Alembic commands ###
