"""evidence

Revision ID: eb4b45667aec
Revises: e9809d0e2cc5
Create Date: 2026-06-25 15:47:20.331907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4b45667aec'
down_revision: Union[str, Sequence[str], None] = 'e9809d0e2cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Enum('move_in', 'move_out', name='evidence_phase'), nullable=False),
    sa.Column('room_label', sa.String(length=200), nullable=True, comment="Free text — no normalization at MVP. e.g. 'master bedroom', 'kitchen'"),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_property_id'), 'evidence', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_property_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
